[package]
name = "asteroid-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bytes = "1.6.1"
future-utils = "0.12.1"
quinn = "0.11.2"
serde = {version = "1", features = ["derive"]}
